version: '3'

services:
  mysql:
    container_name: perks-php_ddd_skeleton-mysql
    image: mysql:8
    ports:
      - "3370:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    command: ["--default-authentication-plugin=mysql_native_password"]

  nginx:
    container_name: perks-ddd-skeleton-nginx
    image: nginx:1.15-alpine
    restart: unless-stopped
    ports:
      - "8065:80"
    volumes:
      - .:/app:delegated
      - ./etc/infrastructure/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  php:
    container_name: perks-php_ddd_skeleton-php
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "9290:9001"
    volumes:
      - .:/app:delegated
    env_file:
      - .env
    depends_on:
      - mysql
