framework:
  test: true

services:
  _defaults:
    autoconfigure: true
    autowire: true

  Perks\Tests\:
    resource: '../../../../tests/src'

  # -- IMPLEMENTATIONS SELECTOR --
  Perks\Shared\Domain\Bus\Event\EventBus: '@Perks\Shared\Infrastructure\Bus\Event\InMemory\InMemorySymfonyEventBus'
