company_get:
  path: /companies
  controller: Perks\Apps\Backoffice\Frontend\Controller\Companies\CompaniesGetWebController
  methods:  [GET]

company_post:
  path: /companies
  controller: Perks\Apps\Backoffice\Frontend\Controller\Companies\CompaniesPostWebController
  methods:  [POST]

company_profile_get:
  path: /company/{companyId}
  controller: Perks\Apps\Backoffice\Frontend\Controller\Companies\CompanyProfileGetWebController
  methods:  [GET]

company_deactivate_put:
  path: /company/{companyId}/deactivate
  controller: Perks\Apps\Backoffice\Frontend\Controller\Companies\CompanyDeactivatePutWebController
  methods:  [GET]

company_perks_post:
  path: /company/{companyId}
  controller: Perks\Apps\Backoffice\Frontend\Controller\Companies\CompanyProfilePerksPostWebController
  methods:  [POST]
